# Funding configuration for this repository.
# Displays a "Sponsor" button on this repo's GitHub page.
# See: https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-sponsor-button-in-your-repository

github: [muhammetsafak]
